### ISSUE TITLE
Broken config

### ISSUE THREAD

**Issue by KristianAN** [KristianAN/nixOS#2]
changes in home/kristian/default.nix are no longer applied to the system when using sudo nixos-rebuild --flake .#laptop .

Any changes in this file does not seem to have any effect on the system. I can not undo anything done in said file either. 

Tried troubleshooting, all out of ideas now.

Thought the hostname was to blame, but it does not seem to be the case. 

```shell
OS: NixOS 23.11.20230718.684c17c (Tapir) x86_64 
Host: LENOVO LNVNB161216 
Kernel: 6.1.38 
Uptime: 21 mins 
Packages: 690 (nix-system), 597 (nix-user) 
Shell: bash 5.2.15 
Resolution: 1920x1080 
WM: sway 
Theme: Breeze-Dark [GTK2/3] 
Icons: breeze-dark [GTK2/3] 
Terminal: kitty 
Terminal Font: Iosevka 12.0 
CPU: AMD Ryzen 5 4500U with Radeon Graphics (6) @ 2.375GHz 
GPU: AMD ATI Renoir 
Memory: 2185MiB / 15371MiB 
```

**Comment by Gako358** [comment]
Try:

```
home-manager switch --flake .#laptop
```

**Comment by KristianAN** [comment]
That was it, and some issues in the config that is now fixed. tytyty
